---
  - hosts: servers
    tasks:
    - name: Run the equivalent of "apt-get update" as a separate step
      apt:
        update_cache: yes
    - name: check apache2 not installed
      apt:
        name: apache2
        state: absent
    - name: install apache2
      apt:
        name: apache2
    - name: ensure apache2  is stopped
      service:
        name: apache2
        state: stopped
    - name: restart apache2  
      service:
        name: apache2
        state: restarted
    - name: ensure apache2  is started
      service:
        name: apache2
        state: started
